; PlatformIO Project Configuration File

[env:adafruit_matrixportal_esp32s3]
upload_port = /dev/cu.usbmodem101
monitor_port = /dev/cu.usbmodem101
platform = espressif32
board = adafruit_matrixportal_esp32s3
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

lib_deps =
  adafruit/Adafruit Protomatter
  adafruit/Adafruit GFX Library
  https://github.com/mrcodetastic/ESP32-HUB75-MatrixPanel-DMA.git

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
